spring:
  config:
    import: optional:file:./.env[.properties] # .env 파일의 환경변수를 주입하여 jar 실행
  jpa:
    hibernate:
      ddl-auto: validate  # 개발 시에는 'create' or 'update', 실제 운영 시 'validate' or 'none'
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    # 커넥션 풀 개수 설정
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10