spring:
  jpa:
    hibernate:
      ddl-auto: validate  # 개발 시에는 'create' or 'update', 실제 운영 시 'validate' or 'none'
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    # 커넥션 풀 개수 설정
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
logging:
  level:
    #    root: debug
    org:
      springframework:
        security: trace
        web:
          servlet: debug
          multipart: debug
        validation: debug