spring:
  config:
    import: optional:classpath:/.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update  # 개발 시에는 'create' or 'update', 실제 운영 시 'validate' or 'none'
  datasource:
    url: jdbc:mariadb://localhost:3306/resolve?useUnicode=true&characterEncoding=utf8
    username: resolve
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    # 커넥션 풀 개수 설정
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10